#R CMD BATCH other_tests.R other_tests.Rout
library(httk)
set.seed(12345)

calc_analytic_css(chem.name="bisphenol a",model="1compartment")
calc_mc_css(chem.name="bisphenol a",model="1compartment")
head(solve_1comp(chem.name="bisphenol a"))
calc_analytic_css(chem.cas="80-05-7",model="1compartment")
calc_mc_css(chem.cas="80-05-7",model="1compartment")
head(solve_1comp(chem.cas="80-05-7"))
calc_analytic_css(parameters=parameterize_1comp(chem.cas="80-05-7"),model="1compartment")
calc_mc_css(parameters=parameterize_1comp(chem.cas="80-05-7"),model="1compartment")
head(solve_1comp(parameters=parameterize_1comp(chem.cas="80-05-7")))
calc_vdist(chem.name="triclosan")
calc_vdist(chem.cas="80-05-7")
params <- parameterize_schmitt(chem.name="triclosan")
calc_vdist(parameters=params)
params <- parameterize_3comp(chem.name="triclosan")
calc_vdist(parameters=params)
params <- parameterize_pbtk(chem.name="triclosan")
calc_vdist(parameters=params)
