#R CMD BATCH other_tests.R other_tests.Rout
library(httk)
set.seed(12345)
calc_analytic_css(chem.name="bisphenol a",model="3compartment")
calc_mc_css(chem.name="bisphenol a",model="3compartment")
head(solve_3comp(chem.name="bisphenol a"))
calc_analytic_css(chem.cas="80-05-7",model="3compartment")
calc_mc_css(chem.cas="80-05-7",model="3compartment")
head(solve_3comp(chem.cas="80-05-7"))
calc_analytic_css(parameters=parameterize_3comp(chem.cas="80-05-7"),model="3compartment")
calc_mc_css(parameters=parameterize_3comp(chem.cas="80-05-7"),model="3compartment")
head(solve_3comp(parameters=parameterize_3comp(chem.cas="80-05-7")))
