#R CMD BATCH other_tests.R other_tests.Rout
library(httk)
set.seed(12345)
calc_analytic_css(chem.name="bisphenol a",model="pbtk")
calc_mc_css(chem.name="bisphenol a",model="pbtk")
head(solve_pbtk(chem.name="bisphenol a"))
calc_analytic_css(chem.cas="80-05-7",model="pbtk")
calc_mc_css(chem.cas="80-05-7",model="pbtk")
head(solve_pbtk(chem.cas="80-05-7"))
calc_analytic_css(parameters=parameterize_pbtk(chem.cas="80-05-7"),model="pbtk")
calc_mc_css(parameters=parameterize_pbtk(chem.cas="80-05-7"),model="pbtk")
head(solve_pbtk(parameters=parameterize_pbtk(chem.cas="80-05-7")))
